name: Release APK and Upload

on:
  workflow_dispatch:  # Enables manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.10.5'  # Specify your Flutter version here

      - name: Set up signing key
        run: |
          if [ ! -z "${{ secrets.KEY_STORE }}" ]; then
            echo "${{ secrets.KEY_STORE }}" | base64 --decode > ./keystore.jks
          else
            echo "KEY_STORE secret is not set. Exiting..."
            exit 1
          fi

      - name: Debug Key Store Presence
        run: |
          if [ -f "./keystore.jks" ]; then
            echo "Keystore is present."
          else
            echo "Keystore is missing."
            exit 1
          fi

      - name: Clean Build
        run: |
          cd /workspaces/Slim/SlimSocial_for_Facebook  # Change this to your actual project directory
          flutter clean

      - name: Build Release APK
        run: |
          cd /workspaces/Slim/SlimSocial_for_Facebook  # Change this to your actual project directory
          flutter build apk --release
        env:  # Set the environment variables here
          RELEASE_KEYSTORE: ./keystore.jks
          RELEASE_KEYSTORE_PASSWORD: ${{ secrets.KEY_STORE_PASSWORD }}
          RELEASE_KEYSTORE_ALIAS: ${{ secrets.KEY_ALIAS }}
          RELEASE_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: List APK files
        run: |
          cd /workspaces/Slim/SlimSocial_for_Facebook  # Change this to your actual project directory
          ls -la build/app/outputs/flutter-apk/

      - name: Upload to GitHub Release
        uses: svenstaro/upload-release-action@v2
        with:
          file: build/app/outputs/flutter-apk/*.apk
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          overwrite: true
          file_glob: true
